### ISSUE TITLE
Auto dispatch of undispatched events

### ISSUE THREAD

**Issue by davideicardi** [deltatre-webplu/NEStore#10]
Eval to auto dispatch of undispatched events after checking if there are undispatched event before writing new events. But eval to use some kind of delay to "ensure" that other active instances are not working on it.
Also think about exceptions in case of error....

**Comment by lucalegora** [comment]
In the first version the client has to implement the retry logic (it could use a little delay to "ensure" that other active instances are not working on it).

**Comment by lucalegora** [comment]
Before writing a new event NEStore tries to redispatch last undispatched commit (set AutoDispatchUndispatchedOnWrite to false to disable it).
