### ISSUE TITLE
Eval to add a convention to serialize get only properties

### ISSUE THREAD

**Issue by davideicardi** [deltatre-webplu/NEStore#12]
Eval to add a convention to allow the serialization of get only properties ( `{get;}` ).

The convention can probably be very similar to:
https://github.com/mongodb/mongo-csharp-driver/blob/master/src/MongoDB.Bson/Serialization/Conventions/ReadWriteMemberFinderConvention.cs

but without the CanWrite check...

**Comment by lucalegora** [comment]
Added ImmutablePocoConvention
